import {
  GoogleTagManager,
  GoogleTagManagerNoscript,
} from '@/libs/GoogleTagManager'

import { geistMono, geistSans } from '@/styles/fonts'

import type { Metadata } from 'next'

import '@/styles/globals.css'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang='en'>
      <GoogleTagManager />
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
        <GoogleTagManagerNoscript />
      </body>
    </html>
  )
}
