// 環境変数のBarrelファイル

export const NEXT_PUBLIC_GTM_ID = process.env.NEXT_PUBLIC_GTM_ID
export const NEXT_PUBLIC_MICROCMS_SERVICE_DOMAIN =
  process.env.NEXT_PUBLIC_MICROCMS_SERVICE_DOMAIN
export const NEXT_PUBLIC_MICROCMS_API_KEY =
  process.env.NEXT_PUBLIC_MICROCMS_API_KEY
export const SERVER_ONLY_MICROCMS_API_KEY =
  process.env.SERVER_ONLY_MICROCMS_API_KEY
export const NEXT_PUBLIC_HOME_URL = process.env.NEXT_PUBLIC_HOME_URL
export const NEXT_RUNTIME = process.env.NEXT_RUNTIME
export const NEXT_PUBLIC_MSW_ENABLED = process.env.NEXT_PUBLIC_MSW_ENABLED
